version: "3.7"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lunch_place
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  lunch_place:
    build: .
    command: "./run.sh"
    volumes:
      - .:/lunch_place
    ports:
      - "8000:8000"
    depends_on:
      - db