# Generated by Django 4.0.4 on 2022-05-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0005_menu_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('poll_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Running', 'running'), ('Finished', 'finished')], default='running', max_length=10)),
                ('winner_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.menu')),
            ],
            options={
                'ordering': ['-poll_date'],
            },
        ),
    ]
