# Generated by Django 4.0.4 on 2022-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_poll_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
