# Generated by Django 4.0.4 on 2022-05-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu_votes'),
        ('poll', '0003_alter_poll_poll_date_alter_poll_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='winner_menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.menu'),
        ),
    ]
