# Generated by Django 4.0.4 on 2022-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_poll_winner_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('finished', 'Finished')], default='running', max_length=10),
        ),
    ]
