# Generated by Django 4.0.4 on 2022-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_poll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('finished', 'finished')], default='running', max_length=10),
        ),
    ]
