# Generated by Django 4.0.4 on 2022-04-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='ratings',
            new_name='rating',
        ),
    ]
